title: Jak zarobić milion złotych
email: madryl95@gmail.com
description: albo uczenie maszynowe w realiach GPW
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
timezone: 'Europe/Warsaw'

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
